apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: metacoding
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root1234
  MYSQL_DATABASE: metadb
  MYSQL_USER: app
  MYSQL_PASSWORD: app1234
